# 应用服务 WEB 访问端口
server:
  port: 8085
#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.bishe.family_financial_system_foreend.mybatis.entity
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/financial_system
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 127.0.0.1 # 更换成自己的地址
    port: 6379
#    password: 1234
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms


